application:
    subscribers:
        settings:
            pump-threshold: 5.0
            dump-threshold: 5.0
            long-liquidation-threshold: 100000.0
            short-liquidation-threshold: 100000.0
